target_column: "target"
to_feature_store: true
test_fraction: 0.3
random_state: 2021
run_name: "full_project"
use_feature_selection: False
feature_selection: "rfe"
model_name: "heart_disease_model"
baseline_model_params:
  n_estimators: 100
  max_depth: 6
  max_features: 20
  random_state: 2021